# Generated by Django 2.1.7 on 2019-06-04 22:26

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriesdate',
            name='category',
        ),
        migrations.AlterUniqueTogether(
            name='categoriesvsdate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='categoriesvsdate',
            name='from_category',
        ),
        migrations.RemoveField(
            model_name='categoriesvsdate',
            name='from_month',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='month',
        ),
        migrations.AddField(
            model_name='categories',
            name='months',
            field=django.contrib.postgres.fields.hstore.HStoreField(default=dict),
        ),
        migrations.DeleteModel(
            name='CategoriesDate',
        ),
        migrations.DeleteModel(
            name='CategoriesVSDate',
        ),
    ]
