# Generated by Django 2.1.7 on 2019-06-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20190604_2226'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultStore',
            fields=[
                ('key', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=100000)),
            ],
        ),
    ]
