# Generated by Django 2.1.7 on 2019-06-05 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_defaultstore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultstore',
            name='value',
            field=models.CharField(default='', max_length=500000),
        ),
    ]
