# Generated by Django 2.1.7 on 2019-07-06 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20190619_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleSentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentence', models.CharField(max_length=10000)),
                ('n_likes', models.IntegerField(default=0)),
                ('importance', models.IntegerField(default=0)),
                ('chronology', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='has_summary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='articlesentence',
            name='article_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article'),
        ),
    ]
