# Generated by Django 2.1.7 on 2019-07-07 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20190706_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesentence',
            options={'verbose_name': 'Summary Sentence', 'verbose_name_plural': 'Summary Sentences'},
        ),
        migrations.AddField(
            model_name='articlesentence',
            name='n_dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='articlesentence',
            name='article_origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_sentences', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='articlesentence',
            name='n_likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to='articles.Article'),
        ),
        migrations.AlterField(
            model_name='githubrepository',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_repos', to='articles.Article'),
        ),
    ]
