# Generated by Django 2.1.7 on 2019-07-23 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_remove_articlesentence_importance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='article',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='users',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='who_added',
        ),
        migrations.RemoveField(
            model_name='blogpostinfo',
            name='blog_post',
        ),
        migrations.AlterUniqueTogether(
            name='blogpostuser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='blogpostuser',
            name='blog_post',
        ),
        migrations.RemoveField(
            model_name='blogpostuser',
            name='user',
        ),
        migrations.RemoveField(
            model_name='githubinfo',
            name='repo',
        ),
        migrations.RemoveField(
            model_name='githubinfo',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='githubrepository',
            name='article',
        ),
        migrations.RemoveField(
            model_name='githubrepository',
            name='users',
        ),
        migrations.RemoveField(
            model_name='githubrepository',
            name='who_added',
        ),
        migrations.AlterUniqueTogether(
            name='githubrepouser',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='githubrepouser',
            name='github_repo',
        ),
        migrations.RemoveField(
            model_name='githubrepouser',
            name='user',
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='BlogPostInfo',
        ),
        migrations.DeleteModel(
            name='BlogPostUser',
        ),
        migrations.DeleteModel(
            name='GitHubInfo',
        ),
        migrations.DeleteModel(
            name='GitHubRepository',
        ),
        migrations.DeleteModel(
            name='GithubRepoUser',
        ),
    ]
