# Generated by Django 2.1.7 on 2019-07-24 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0011_auto_20190724_0240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reddit',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.Resource')),
                ('title', models.CharField(blank=True, default=None, max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, default=None, verbose_name='description')),
                ('image', models.URLField(blank=True, default=None, verbose_name='image_url')),
            ],
            bases=('articles.resource',),
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.Resource')),
                ('title', models.CharField(blank=True, default=None, max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, default=None, verbose_name='description')),
                ('image', models.URLField(blank=True, default=None, verbose_name='image_url')),
            ],
            bases=('articles.resource',),
        ),
        migrations.CreateModel(
            name='WebSite',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.Resource')),
                ('title', models.CharField(blank=True, default=None, max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, default=None, verbose_name='description')),
                ('image', models.URLField(blank=True, default=None, verbose_name='image_url')),
            ],
            bases=('articles.resource',),
        ),
        migrations.CreateModel(
            name='YouTube',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='articles.Resource')),
                ('title', models.CharField(blank=True, default=None, max_length=300, verbose_name='title')),
                ('description', models.TextField(blank=True, default=None, verbose_name='description')),
                ('image', models.URLField(blank=True, default=None, verbose_name='image_url')),
            ],
            bases=('articles.resource',),
        ),
    ]
