# Generated by Django 2.1.7 on 2019-07-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0012_reddit_slides_website_youtube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.URLField(default=None, null=True, verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='github',
            name='description',
            field=models.TextField(default='', null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='github',
            name='framework',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='framework'),
        ),
        migrations.AlterField(
            model_name='github',
            name='is_official',
            field=models.BooleanField(default=False, null=True, verbose_name='is_official'),
        ),
        migrations.AlterField(
            model_name='github',
            name='language',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='language'),
        ),
        migrations.AlterField(
            model_name='github',
            name='n_stars',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='stars'),
        ),
        migrations.AlterField(
            model_name='github',
            name='title',
            field=models.CharField(max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='reddit',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='reddit',
            name='image',
            field=models.URLField(default=None, null=True, verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='reddit',
            name='title',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='image',
            field=models.URLField(default=None, null=True, verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='slides',
            name='title',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='website',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='website',
            name='image',
            field=models.URLField(default=None, null=True, verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='website',
            name='title',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='description',
            field=models.TextField(default=None, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='image',
            field=models.URLField(default=None, null=True, verbose_name='image_url'),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='title',
            field=models.CharField(default=None, max_length=300, null=True, verbose_name='title'),
        ),
    ]
