# Generated by Django 2.1.7 on 2019-08-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0013_auto_20190724_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='has_sitemap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='has_sitemap',
            field=models.BooleanField(default=False),
        ),
    ]
