# Generated by Django 2.1.7 on 2019-07-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='second_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
