# Generated by Django 2.1.7 on 2019-08-21 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20190820_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='premiumsubscription',
            name='is_daily_mail',
            field=models.BooleanField(default=True, verbose_name='Is daily mail'),
        ),
        migrations.AddField(
            model_name='premiumsubscription',
            name='is_weekly_mail',
            field=models.BooleanField(default=True, verbose_name='Is weekly mail'),
        ),
    ]
