# Generated by Django 2.1.7 on 2019-10-11 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_requestdemo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('info', models.TextField(max_length=10000)),
                ('date_created', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
