# Generated by Django 2.1.7 on 2019-10-12 17:19

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(storage=core.models.MyFileSystemStorage(), upload_to=''),
        ),
    ]
