# Generated by Django 2.1.7 on 2019-03-26 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('model', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dal_field', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(null=True)),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'n/a'), (1, 'add'), (2, 'change'), (3, 'delete')], default=0)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atl_model_application', to='log.Application')),
            ],
            options={
                'verbose_name': 'Changelog',
                'verbose_name_plural': 'Changelogs',
            },
        ),
        migrations.CreateModel(
            name='ModelChangelog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelModification',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ModelObject',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.CharField(max_length=255, null=True)),
                ('field', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Field')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atl_modelobject_application', to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uri', models.URLField()),
                ('method', models.CharField(max_length=64)),
                ('status', models.PositiveSmallIntegerField(null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.Application')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
        migrations.CreateModel(
            name='Unspecified',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.TextField(null=True)),
                ('level', models.PositiveSmallIntegerField(default=20)),
                ('file', models.CharField(max_length=255, null=True)),
                ('line', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Non DAL Message',
                'verbose_name_plural': 'Non DAL Messages',
            },
        ),
        migrations.AddField(
            model_name='modelmodification',
            name='currently',
            field=models.ManyToManyField(related_name='changelog_current', to='log.ModelObject'),
        ),
        migrations.AddField(
            model_name='modelmodification',
            name='previously',
            field=models.ManyToManyField(related_name='changelog_previous', to='log.ModelObject'),
        ),
        migrations.AddField(
            model_name='modelchangelog',
            name='information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.ModelObject'),
        ),
        migrations.AddField(
            model_name='modelchangelog',
            name='inserted',
            field=models.ManyToManyField(related_name='changelog_inserted', to='log.ModelObject'),
        ),
        migrations.AddField(
            model_name='modelchangelog',
            name='modification',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.ModelModification'),
        ),
        migrations.AddField(
            model_name='modelchangelog',
            name='removed',
            field=models.ManyToManyField(related_name='changelog_removed', to='log.ModelObject'),
        ),
        migrations.AddField(
            model_name='model',
            name='information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atl_model_information', to='log.ModelObject'),
        ),
        migrations.AddField(
            model_name='model',
            name='modification',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='log.ModelChangelog'),
        ),
        migrations.AddField(
            model_name='model',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
