# Generated by Django 2.1.7 on 2019-04-18 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.TextField(max_length=1000)),
                ('time', models.DateTimeField(auto_now=True)),
                ('action', models.PositiveSmallIntegerField(choices=[(0, 'other'), (1, 'add DB'), (2, 'change DB'), (3, 'delete DB'), (4, 'move')], default=0)),
                ('args', models.TextField(max_length=2000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
