# Generated by Django 2.1.7 on 2019-04-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_logmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'other'), (1, 'append'), (2, 'change'), (3, 'delete'), (4, 'move')], default=0),
        ),
    ]
