# Generated by Django 2.1.7 on 2019-04-18 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_auto_20190418_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'other'), (1, 'move')], default=0),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
