# Generated by Django 2.1.7 on 2019-04-18 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_auto_20190418_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='action',
            field=models.PositiveSmallIntegerField(choices=[(0, 'other'), (1, 'move'), (2, 'login'), (3, 'logout'), (4, 'search')], default=0),
        ),
    ]
